import streamlit as st
import streamlit.components.v1 as components

# 1. 페이지 및 레이아웃 설정
st.set_page_config(page_title="3D 볼링 게임", page_icon="🎳", layout="wide")

st.title("🎳 스트림릿 고퀄리티 3D 볼링 게임")
st.write("아래 3D 화면을 클릭하고 **마우스를 드래그해서 앞으로 던지면** 공이 굴러갑니다!")

# 2. 삼중 따옴표 에러를 피하기 위한 리스트 결합 방식
html_lines = [
    '<!DOCTYPE html>',
    '<html lang="ko">',
    '<head>',
    '    <meta charset="UTF-8">',
    '    <title>3D Bowling Game</title>',
    '    <style>',
    '        body { margin: 0; overflow: hidden; background-color: #1a1a1a; font-family: sans-serif; }',
    '        canvas { display: block; }',
    '        #info { position: absolute; top: 10px; left: 10px; color: white; background: rgba(0,0,0,0.7); padding: 10px; border-radius: 5px; pointer-events: none; z-index: 10; }',
    '        #score-board { position: absolute; top: 10px; right: 10px; color: #fff; background: rgba(0,0,0,0.8); padding: 15px; border-radius: 8px; border: 2px solid #333; font-size: 18px; z-index: 10; }',
    '        #reset-btn { position: absolute; bottom: 20px; left: 50%; transform: translateX(-50%); padding: 12px 24px; font-size: 16px; background-color: #ff4b4b; color: white; border: none; border-radius: 5px; cursor: pointer; font-weight: bold; z-index: 10; }',
    '        #reset-btn:hover { background-color: #ff3333; }',
    '    </style>',
    '    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>',
    '</head>',
    '<body>',
    '    <div id="info">🕹️ 조작법: 공을 마우스로 붙잡고 앞(위쪽)으로 빠르게 드래그해서 던지세요!</div>',
    '    <div id="score-board">🎳 쓰러진 핀: <span id="score">0</span> / 10</div>',
    '    <button id="reset-btn" onclick="resetGame()">🎳 다시 던지기 (리셋)</button>',
    '    <script>',
    '        let scene, camera, renderer, ball, lane;',
    '        let pins = [];',
    '        let pinPositions = [];',
    '        let ballVelocity = { x: 0, y: 0, z: 0 };',
    '        let isThrown = false;',
    '        let gravity = -0.005;',
    '        let isMouseDown = false;',
    '        let mouseStart = { x: 0, y: 0, time: 0 };',
    '        init();',
    '        animate();',
    '        function init() {',
    '            scene = new THREE.Scene();',
    '            scene.background = new THREE.Color(0x14141f);',
    '            camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 1000);',
    '            camera.position.set(0, 5, 18);',
    '            camera.lookAt(0, 1, -10);',
    '            renderer = new THREE.WebGLRenderer({ antialias: true });',
    '            renderer.setSize(window.innerWidth, window.innerHeight);',
    '            renderer.shadowMap.enabled = true;',
    '            document.body.appendChild(renderer.domElement);',
    '            const ambientLight = new THREE.AmbientLight(0xffffff, 0.6);',
    '            scene.add(ambientLight);',
    '            const dirLight = new THREE.DirectionalLight(0xffffff, 0.8);',
    '            dirLight.position.set(5, 15, 10);',
    '            dirLight.castShadow = true;',
    '            scene.add(dirLight);',
    '            const laneGeo = new THREE.BoxGeometry(4, 0.2, 30);',
    '            const laneMat = new THREE.MeshStandardMaterial({ color: 0xd2a679, roughness: 0.1 });',
    '            lane = new THREE.Mesh(laneGeo, laneMat);',
    '            lane.position.set(0, -0.1, -5);',
    '            lane.receiveShadow = true;',
    '            scene.add(lane);',
    '            const gutterMat = new THREE.MeshStandardMaterial({ color: 0x333333 });',
    '            const leftGutter = new THREE.Mesh(new THREE.BoxGeometry(0.5, 0.2, 30), gutterMat);',
    '            leftGutter.position.set(-2.25, -0.1, -5);',
    '            const rightGutter = new THREE.Mesh(new THREE.BoxGeometry(0.5, 0.2, 30), gutterMat);',
    '            rightGutter.position.set(2.25, -0.1, -5);',
    '            scene.add(leftGutter, rightGutter);',
    '            const ballGeo = new THREE.SphereGeometry(0.4, 32, 32);',
    '            const ballMat = new THREE.MeshStandardMaterial({ color: 0x0055ff, roughness: 0.2, metalness: 0.5 });',
    '            ball = new THREE.Mesh(ballGeo, ballMat);',
    '            ball.position.set(0, 0.4, 8);',
    '            ball.castShadow = true;',
    '            scene.add(ball);',
    '            const rowSpacing = -0.6;',
    '            const colSpacing = 0.4;',
    '            for (let row = 0; row < 4; row++) {',
    '                let count = row + 1;',
    '                let startX = -((count - 1) * colSpacing) / 2;',
    '                for (let col = 0; col < count; col++) {',
    '                    pinPositions.push({ x: startX + col * colSpacing, y: 0.5, z: -15 + row * rowSpacing });',
    '                }',
    '            }',
    '            createPins();',
    '            window.addEventListener("mousedown", onMouseDown);',
    '            window.addEventListener("mouseup", onMouseUp);',
    '            window.addEventListener("resize", onWindowResize);',
    '        }',
    '        function createPins() {',
    '            pins.forEach(p => scene.remove(p));',
    '            pins = [];',
    '            const pinGeo = new THREE.CylinderGeometry(0.1, 0.18, 1.0, 16);',
    '            const pinMat = new THREE.MeshStandardMaterial({ color: 0xffffff, roughness: 0.5 });',
    '            pinPositions.forEach((pos) => {',
    '                const pin = new THREE.Mesh(pinGeo, pinMat);',
    '                pin.position.set(pos.x, pos.y, pos.z);',
    '                pin.castShadow = true;',
    '                pin.userData = { isActive: true, vel: {x: 0, y: 0, z: 0}, rot: {x: 0, y: 0, z: 0} };',
    '                scene.add(pin);',
    '                pins.push(pin);',
    '            });',
    '        }',
    '        function onMouseDown(e) {',
    '            if (isThrown) return;',
    '            isMouseDown = true;',
    '            mouseStart.x = e.clientX;',
    '            mouseStart.y = e.clientY;',
    '            mouseStart.time = Date.now();',
    '        }',
    '        function onMouseUp(e) {',
    '            if (!isMouseDown || isThrown) return;',
    '            isMouseDown = false;',
    '            let duration = Date.now() - mouseStart.time || 1;',
    '            let deltaX = e.clientX - mouseStart.x;',
    '            let deltaY = e.clientY - mouseStart.y;',
    '            if (deltaY < -20) {',
    '                isThrown = true;',
    '                ballVelocity.z = (deltaY / duration) * 0.15;',
    '                ballVelocity.x = (deltaX / duration) * 0.05;',
    '                ballVelocity.y = 0;',
    '            }',
    '        }',
    '        function resetGame() {',
    '            isThrown = false;',
    '            ball.position.set(0, 0.4, 8);',
    '            ballVelocity = { x: 0, y: 0, z: 0 };',
    '            createPins();',
    '            document.getElementById("score").innerText = "0";',
    '        }',
    '        function onWindowResize() {',
    '            camera.aspect = window.innerWidth / window.innerHeight;',
    '            camera.updateProjectionMatrix();',
    '            renderer.setSize(window.innerWidth, window.innerHeight);',
    '        }',
    '        function animate() {',
    '            requestAnimationFrame(animate);',
    '            if (isThrown) {',
    '                ball.position.x += ballVelocity.x;',
    '                ball.position.z += ballVelocity.z;',
    '                ball.rotation.x -= ballVelocity.z * 2;',
    '                if (Math.abs(ball.position.x) > 2.0) {',
    '                    ballVelocity.x = 0;',
    '                    ball.position.y = 0.2;',
    '                }',
    '                pins.forEach(pin => {',
    '                    if (!pin.userData.isActive) return;',
    '                    let dist = ball.position.distanceTo(pin.position);',
    '                    if (dist < 0.58) {',
    '                        pin.userData.isActive = false;',
    '                        pin.userData.vel.z = ballVelocity.z * 0.6;',
    '                        pin.userData.vel.x = (pin.position.x - ball.position.x) * 0.5 + ballVelocity.x * 0.4;',
    '                        pin.userData.vel.y = Math.abs(ballVelocity.z) * 0.3;',
    '                        pin.userData.rot.x = -2.0;',
    '                        pin.userData.rot.z = (pin.position.x - ball.position.x) * 5;',
    '                    }',
    '                });',
    '                for (let i = 0; i < pins.length; i++) {',
    '                    for (let j = 0; j < pins.length; j++) {',
    '                        if (i === j) continue;',
    '                        let p1 = pins[i]; let p2 = pins[j];',
    '                        if (!p1.userData.isActive && p2.userData.isActive) {',
    '                            let dist = p1.position.distanceTo(p2.position);',
    '                            if (dist < 0.5) {',
    '                                p2.userData.isActive = false;',
    '                                p2.userData.vel.z = p1.userData.vel.z * 0.6;',
    '                                p2.userData.vel.x = (p2.position.x - p1.position.x) * 0.8;',
    '                                p2.userData.vel.y = Math.abs(p1.userData.vel.z) * 0.2;',
    '                                p2.userData.rot.x = -1.5;',
    '                            }',
    '                        }',
    '                    }',
    '                }',
    '            }',
    '            let fallenCount = 0;',
    '            pins.forEach(pin => {',
    '                if (!pin.userData.isActive) {',
    '                    pin.userData.vel.y += gravity;',
    '                    pin.position.x += pin.userData.vel.x;',
    '                    pin.position.y += pin.userData.vel.y;',
    '                    pin.position.z += pin.userData.vel.z;',
    '                    pin.rotation.x += pin.userData.rot.x * 0.1;',
    '                    pin.rotation.z += pin.userData.rot.z * 0.1;',
    '                    if (pin.position.y < 0.2) {',
    '                        pin.position.y = 0.2;',
    '                        pin.userData.vel.y = 0;',
    '                        pin.userData.vel.x *= 0.8;',
    '                        pin.userData.vel.z *= 0.8;',
    '                    }',
    '                    fallenCount++;',
    '                }',
    '            });',
    '            document.getElementById("score").innerText = fallenCount;',
    '            renderer.render(scene, camera);',
    '        }',
    '    </script>',
    '</body>',
    '</html>'
]

# 리스트 컴포넌트를 줄바꿈 문자로 하나의 HTML 문자열로 병합
game_html_code = "\n".join(html_lines)

# 3. 렌더링 실행
components.html(game_html_code, height=650, scrolling=False)
